using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Diablo3GearHelper.Types
{
    public class MaxStatLookupTable
    {
        private static MaxStatLookupTable instance;

        public static MaxStatLookupTable Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new MaxStatLookupTable();
                }
                return instance;
            }
        }

        public readonly MaxStatTableEntry[] Table =
        {
            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),

            // Helm
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Intelligence, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Dexterity, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Strength, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Vitality, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AverageDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitChance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.CriticalHitDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentDamageAgainstElites, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AttackSpeed, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PercentLife, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BonusArmor, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.AllResistances, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.PoisonResistance, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.FireDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ColdDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.LightningDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.Sockets, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneTorrentDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.ArcaneOrbDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.DisintegrateDamage, ItemQuality.Rare, 750.0f),
            new MaxStatTableEntry(ItemSlot.Helm, AffixType.BlackHoleDamage, ItemQuality.Rare, 750.0f),
        };

        public MaxStatTableEntry this[int i]
        {
            get
            {
                return this.Table[i];
            }
        }
    }

    public class MaxStatTableEntry
    {
        public ItemSlot Slot;
        public AffixType Stat;
        public ItemQuality Quality;
        public float MaxValue;

        public MaxStatTableEntry() { }

        public MaxStatTableEntry(ItemSlot slot, AffixType stat, ItemQuality quality, float max)
        {
            this.Slot = slot;
            this.Stat = stat;
            this.Quality = quality;
            this.MaxValue = max;
        }
    }
}
